version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    timezone: Asia/Tokyo
  open-pull-requests-limit: 100
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.7
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
  - dependency-name: three
    versions:
    - 0.125.1
    - 0.126.0
    - 0.126.1
    - 0.127.0
  - dependency-name: navigo
    versions:
    - 8.10.1
    - 8.11.0
    - 8.8.0
    - 8.8.11
    - 8.8.12
    - 8.8.2
    - 8.8.4
    - 8.8.6
    - 8.8.7
    - 8.9.0
    - 8.9.1
