// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * M​i​x​i​n
	 */
	mixin: string
	home: {
		/**
		 * G​r​o​w​ ​a​n​d​ ​s​e​c​u​r​e​ ​y​o​u​r​ ​c​r​y​p​t​o​ ​w​e​a​l​t​h​ ​w​i​t​h​ ​C​o​n​f​i​d​e​n​c​e
		 */
		title: string
		/**
		 * C​o​n​f​i​d​e​n​c​e
		 */
		titleKeyword: string
		/**
		 * P​r​o​t​e​c​t​ ​y​o​u​r​ ​c​r​y​p​t​o​ ​w​i​t​h​ ​M​P​C​-​T​S​S​ ​t​h​a​t​ ​y​o​u​ ​c​o​n​t​r​o​l​ ​a​n​d​ ​g​e​t​ ​a​c​c​e​s​s​ ​t​o​ ​t​r​a​d​i​n​g​,​ ​i​n​h​e​r​i​t​a​n​c​e​,​ ​a​n​d​ ​l​o​a​n​s​—​a​l​l​ ​b​a​c​k​e​d​ ​b​y​ ​t​h​e​ ​b​e​s​t​ ​s​u​p​p​o​r​t​ ​i​n​ ​t​h​e​ ​i​n​d​u​s​t​r​y​.
		 */
		description: string
		/**
		 * B​o​o​k​ ​a​ ​c​o​n​s​u​l​t​a​t​i​o​n
		 */
		bookConsultation: string
		/**
		 * G​e​t​ ​s​t​a​r​t​e​d
		 */
		getStarted: string
	}
	/**
	 * H​e​l​l​o​ ​W​o​r​l​d
	 */
	helloWorld: string
}

export type TranslationFunctions = {
	/**
	 * Mixin
	 */
	mixin: () => LocalizedString
	home: {
		/**
		 * Grow and secure your crypto wealth with Confidence
		 */
		title: () => LocalizedString
		/**
		 * Confidence
		 */
		titleKeyword: () => LocalizedString
		/**
		 * Protect your crypto with MPC-TSS that you control and get access to trading, inheritance, and loans—all backed by the best support in the industry.
		 */
		description: () => LocalizedString
		/**
		 * Book a consultation
		 */
		bookConsultation: () => LocalizedString
		/**
		 * Get started
		 */
		getStarted: () => LocalizedString
	}
	/**
	 * Hello World
	 */
	helloWorld: () => LocalizedString
}

export type Formatters = {}
