name: Publish Release

on:
  push:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: "latest"

      - name: Install dependencies
        run: pnpm i

      - name: Install dependencies for SSG
        working-directory: ssg/
        run: pnpm i

      - name: Build SPA
        working-directory: .
        run: pnpm run build

      - name: Build SSG
        working-directory: ssg/
        run: pnpm run build

      - name: Create release directory
        run: mkdir release

      - name: Move files to release directory
        run: |
          mv dist release/spa
          mv ssg/build release/ssg

      - name: Remove robots.txt from SSG
        run: rm release/ssg/robots.txt

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release.zip release

      - name: Show files
        run: ls
