on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 'latest'

      - name: Install dependencies
        run: pnpm i

      - name: Install dependencies for SSG
        working-directory: ssg/
        run: pnpm i

      - name: Build SPA
        working-directory: .
        run: pnpm run dist

      - name: Build SSG
        working-directory: ssg/
        run: pnpm run build

      - name: Create release directory
        run: mkdir release

      - name: Move files to release directory
        run: |
          mv dist release/spa
          mv ssg/build release/ssg

      - name: Remove robots.txt
        run: rm release/ssg/robots.txt && rm release/ssg/**/robots.txt

      - name: Remove sitemap.xml
        run: rm release/ssg/sitemap.xml && rm release/ssg/**/sitemap.xml

      - name: Remove .well-known for another language
        run: rm -r release/ssg/*/.well-known

      - name: Show files for release/ssg
        working-directory: release/ssg
        run: ls -a

      - name: Show files for release/ssg/zh
        working-directory: release/ssg/zh
        run: ls -a
